In [1]:
# value iteration
import numpy as np
import GridWorld_v1

gamma = 0.9
rows = 5
columns = 5

gridworld = GridWorld_v1.GridWorld_v1(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
gridworld.show()

value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.argmax(qtable, axis=1)

gridworld.showPolicy(policy)

pre_value = value.copy() + 1
cnt = 0

while (np.sum((pre_value - value) ** 2)) > 0.001:
    pre_value = value.copy() # 保存结果 在下一个iteration中做对比 
    cnt = cnt + 1
    # if cnt > 1000:
    #     break

    for i in range(rows * columns):
        for j in range(5):
            score, nextState = gridworld.getScore(i, j)
            qtable[i][j] = score + gamma * value[nextState]
    policy = np.argmax(qtable, axis=1)
    value = np.max(qtable, axis=1)
    print(value.reshape(rows, columns))
    print(policy.reshape(rows, columns))

print(value.reshape(rows, columns))
print(policy.reshape(rows, columns))
print(cnt)
gridworld.showPolicy(policy)

⬜️⬜️⬜️⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
🚫⬜️✅⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⏫️⬆️✅⬆️⬆️
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 1 4 3 0]]
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.9 0.  0. ]
 [0.  0.9 1.9 0.9 0. ]
 [0.9 1.9 1.9 1.9 0.9]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 1 2 2 0]
 [1 1 4 3 3]]
[[0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.   0.81 1.71 0.81 0.  ]
 [0.81 1.71 2.71 1.71 0.81]
 [1.71 2.71 2.71 2.71 1.71]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 2 2 2 0]
 [1 1 2 2 2]
 [1 1 4 3 3]]
[[0.    0.    0.    0.    0.   ]
 [0.    0.729 0.    0.729 0.   ]
 [0.729 1.539 2.439 1.539 0.729]
 [1.539 2.439 3.439 2.439 1.539]
 [2.439 3.439 3.439 3.439 2.439]]
[[1 1 1 1 2]
 [0 2 0 2 0]
 [1 2 2 2 2]
 [1 1 2 2 2]
 [1 1 4 3 3]]
[[0.     0.6561 0.     0.6561 0.    ]
 [0.6561 1.3851 0.6561 1.3851 0.6561]
 [1.3851 2.1951 3.0951 2.1951 1.3851]
 [

In [2]:
# (truncated) policy iteration
import numpy as np
import GridWorld_v1

gamma = 0.9
rows = 5
columns = 5

gridworld = GridWorld_v1.GridWorld_v1(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
gridworld.show()

value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.argmax(qtable, axis=1)

gridworld.showPolicy(policy)
policy = np.random.randint(0, 5, size=rows * columns) # 随机给定一个策略
gridworld.showPolicy(policy)

pre_value = value.copy() + 1
cnt = 0
while (np.sum((pre_value - value) ** 2)) > 0.001:

    truncated = 100
    pre_value = value.copy()
    
    value0 = value.copy() + 1 # value收敛

    while (np.sum((value0 - value) ** 2)) > 0.001:
        value0 = value.copy()
        truncated = truncated - 1
        if truncated < 0:
            break
        for i in range(rows * columns):
            j = policy[i]
            score, nextState = gridworld.getScore(i, j)
            value[i] = score + gamma * value0[nextState]
    
    for i in range(rows * columns):
        for j in range(5):
            score, nextState = gridworld.getScore(i, j)
            qtable[i][j] = score + gamma * value[nextState]
    
    cnt = cnt + 1
    policy = np.argmax(qtable, axis=1)
    print(value.reshape(rows, columns))
    print(policy.reshape(rows, columns))

print(value.reshape(rows, columns))
print(policy.reshape(rows, columns))
print(cnt)
gridworld.showPolicy(policy)

⬜️⬜️⬜️⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
🚫⬜️✅⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⏫️⬆️✅⬆️⬆️
🔄⬅️⬆️⬇️⬆️
➡️➡️⬆️➡️➡️
⬇️➡️⏫️⬇️⬅️
⬆️⬅️⬇️🔄⬇️
⏪⬆️✅🔄⬆️
[[  0.           0.          -9.92144833  -8.02144833  -9.92144833]
 [ -7.21144833  -8.02144833  -8.92144833  -8.92144833  -9.92144833]
 [  0.         -17.21144833  -8.02144833   0.           0.        ]
 [  0.           0.           1.           0.           0.        ]
 [ -9.92144833   0.           0.           0.           0.        ]]
[[1 3 3 4 3]
 [0 0 3 2 2]
 [2 2 2 1 2]
 [0 1 2 3 0]
 [0 1 4 3 0]]
[[ 0.          0.          0.         -0.07001091 -0.07001091]
 [ 0.          0.          0.          0.          0.        ]
 [ 0.          8.01272036  8.91272036  0.          0.        ]
 [ 0.          8.91272036  9.91272036  8.91272036  0.        ]
 [ 0.          9.91272036  9.91272036  9.91272036  0.        ]]
[[1 1 2 2 2]
 [0 2 0 1 2]
 [1 2 2 2 0]
 [1 1 2 2 3]
 [1 1 4 3 3]]
[[0.        0.        0.        0.        0.       ]
 [

In [3]:
# MC Basic
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()
gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 100
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = 0
pre_qtable = qtable.copy() + 1
while (np.sum(pre_qtable - qtable) ** 2) > 0.001:
    cnt = cnt + 1
    pre_qtable = qtable.copy()
    for i in range(rows * columns):
        for j in range(5):
            Trajectory = gridworld.getTrajectoryScore(i, j, policy, trajectorySteps)
            tmp = Trajectory[trajectorySteps][2]
            for k in range(trajectorySteps - 1, -1, -1):
                tmp = Trajectory[k][2] + gamma * tmp
            qtable[i][j] = tmp
    # print(qtable)
    policy = np.eye(5)[np.argmax(qtable, axis=1)]

    gridworld.showPolicy(policy)
    print(np.sum(pre_qtable - qtable) ** 2)
print(qtable.reshape(rows * columns, 5))
print(policy.reshape(rows * columns, 5))
print(cnt)
# gridworld.showPolicy(policy)

endtime = time.time()

print(endtime - start_time)

⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
➡️⬇️⬅️➡️⬇️
⬆️⬆️⬅️➡️⬆️
⬆️⬆️⏬➡️⬆️
⬆️➡️⬇️⬅️⬆️
⏫️➡️✅⬅️⬆️
1118919.943839395
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬇️⏬⬇️⬆️
➡️➡️⬇️⬇️⬅️
⏩️➡️✅⬅️⬅️
1595880.794875436
➡️➡️➡️➡️⬇️
⬆️⬇️⬆️⬇️⬆️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
51434.98702378699
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
17217.43368362414
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
51678.514203809405
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
0.0
[[ 4.31417095  5.90466095  5.90466095  4.31417095  5.31417095]
 [ 4.90466095  5.31417095  6.56076095  5.31417095  5.90466095]
 [ 4.31417095  5.90466095  5.90466095  5.90466095  5.31417095]
 [ 4.90466095  5.31417095  6.56076095  5.31417095  5.90466095]
 [ 4.31417095  4.31417095  5.90466095  5.90466095  5.31417095]
 [ 5.31417095  6.56076095  6.56076095  4.90466095  5.90466095]
 [ 5.90466095  5.90466095  7.28976095  5.90466095  6.56076095]
 [ 5.31417095  6.56076095 -1.90023905  6.56076095  5.90466095]
 [ 5.90466095  5.90466095  7.2897

In [4]:
# MC exploring starts
# first_visit strategy
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()

gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 100
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = 0
pre_qtable = qtable.copy() + 1


while (np.sum(pre_qtable - qtable) ** 2) > 0.001:
    cnt += 1
    pre_qtable = qtable.copy()
    for i in range(rows * columns):
        for j in range(5):
            Trajectory = gridworld.getTrajectoryScore(i, j, policy, trajectorySteps)
            _, _, score, _, _ = Trajectory[trajectorySteps]
            for k in range(trajectorySteps - 1, -1, -1):
                tmpstate, tmpaction, tmpscore, _, _ = Trajectory[k]
                score = tmpscore + gamma * score
                qtable[tmpstate][tmpaction] = score
    
    policy = np.eye(5)[np.argmax(qtable, axis=1)]
    gridworld.showPolicy(policy)
    print(np.sum(pre_qtable - qtable) ** 2)
print(qtable.reshape(rows * columns, 5))
print(policy.reshape(rows * columns, 5))
print(cnt)

endtime = time.time()

print(endtime - start_time)


⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
➡️⬇️⬅️➡️⬇️
⬆️⬆️⬅️➡️⬆️
⬆️⬆️⏬➡️⬆️
⬆️➡️⬇️⬅️⬆️
⏫️➡️✅⬅️⬆️
1118919.2695262474
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬇️⏬⬇️⬆️
➡️⬇️⬇️⬇️⬅️
⏩️➡️✅⬅️⬅️
1595879.3706723428
➡️➡️➡️➡️⬇️
⬆️⬇️⬆️⬇️⬆️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬅️⬇️
⏩️➡️✅⬅️⬅️
51434.88647618398
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
⬇️⬇️⏬⬇️⬅️
➡️⬇️⬇️⬇️⬅️
⏩️➡️✅⬅️⬅️
17217.40580155726
⬇️⬇️⬇️⬇️⬅️
⬇️⬇️⬅️⬇️⬅️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬅️⬇️
⏩️➡️✅⬅️⬅️
51678.40417483602
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
⬇️⬇️⏬⬇️⬅️
➡️⬇️⬇️⬇️⬅️
⏩️➡️✅⬅️⬅️
3.4839896833810614e-09
[[ 4.31417095  5.90466095  5.90463439  4.31417095  5.31417095]
 [ 4.90466095  5.31417095  6.56073439  5.31417095  5.90466095]
 [ 4.31417095  5.90466095  5.90463439  5.90466095  5.31417095]
 [ 4.90466095  5.31417095  6.56070487  5.31417095  5.90466095]
 [ 4.31417095  4.31417095  5.90466095  5.90463439  5.31417095]
 [ 5.31417095  6.56076095  6.56073439  4.90466095  5.90466095]
 [ 5.90466095  5.90466095  7.28970487  5.90466095  6.56076095]
 [ 5.31417095  6.56076095 -1.90023905  6.56073439  5.90466095]
 [ 5.90466095

In [5]:
# MC epsilon greedy
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()

gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 200
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = [0 for _ in range(25)]

episode_num = 200
epsilon = 0.1

for episode in range(episode_num):
    if epsilon > 0.001:
        epsilon -= 0.001
    else:
        epsilon = 0.001
    
    prob1 = 1 - epsilon * (4 / 5)
    prob2 = epsilon / 5
    print("trajectorySteps",trajectorySteps)
    print(f"epision:{epsilon}, prob1:{prob1}, prob2:{prob2}")
    
    policy_epsilon = np.zeros_like(policy, dtype=float)
    policy_epsilon[policy == 1] = prob1
    policy_epsilon[policy == 0] = prob2
    i = np.random.randint(0, 24)
    j = np.random.randint(0, 4)

    # cnt = [0 for _ in range(25)]
    qtable_rewards = [[0 for _ in range(5)] for _ in range(rows * columns)] 
    qtable_nums = [[0 for _ in range(5)] for _ in range(rows * columns)]
    Trajectory = gridworld.getTrajectoryScore(i, j, policy_epsilon, trajectorySteps)
    _, _, score, _, _ = Trajectory[trajectorySteps]
    for k in range(trajectorySteps - 1, -1, -1):
        tmpstate, tmpaction, tmpscore, _, _ = Trajectory[k]
        cnt[tmpstate] += 1
        score = tmpscore + gamma * score
        qtable_rewards[tmpstate][tmpaction] += score
        qtable_nums[tmpstate][tmpaction] += 1
        qtable[tmpstate][tmpaction] = qtable_rewards[tmpstate][tmpaction] / qtable_nums[tmpstate][tmpaction]
    
    values = []
    for i in range(25):
        value = 0
        for j in range(5):
            value += policy_epsilon[i][j] * qtable[i][j]
        values.append(value)
    print(np.array(values).mean())
    gridworld.showPolicy(policy)
    policy = np.eye(5)[np.argmax(qtable,axis=1)]
    policy_epsilon = np.zeros_like(policy, dtype=float)
    policy_epsilon[policy == 1] = prob1
    policy_epsilon[policy == 0] = prob2

    # print(np.array(cnt).reshape(5, 5))
print(np.array(cnt).reshape(5, 5))
endtime = time.time()

print(endtime - start_time)


⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
trajectorySteps 200
epision:0.099, prob1:0.9208, prob2:0.0198
-6.628880625496459
⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
trajectorySteps 200
epision:0.098, prob1:0.9216, prob2:0.0196
-2.337201849502099
⬆️⬆️⬆️➡️⬆️
⬇️➡️➡️⬆️➡️
⬆️⬆️⏩️⬆️⬇️
⬆️⬆️⬇️⬆️➡️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.097, prob1:0.9224, prob2:0.0194
-1.3783828428880396
⬆️⬆️⬆️⬅️⬇️
⬇️➡️➡️➡️⬆️
⬆️⬆️⏩️⬇️🔄
⬆️⬆️⬇️⬇️⬇️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.096, prob1:0.9232, prob2:0.019200000000000002
-0.3358884845692183
⬆️⬇️🔄🔄➡️
⬇️⬇️🔄⬇️🔄
⬆️➡️⏩️⬇️🔄
⬆️⬆️⬇️⬇️⬇️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.095, prob1:0.9239999999999999, prob2:0.019
-7.15242980357739
⬆️➡️🔄🔄➡️
⬇️⬇️🔄🔄🔄
⬆️➡️⏩️⬅️🔄
⬆️⬆️⬇️⬅️⬅️
⏫️⬆️✅⬇️➡️
trajectorySteps 200
epision:0.094, prob1:0.9248, prob2:0.0188
0.12397357523218963
⬆️➡️🔄🔄➡️
⬇️⬅️➡️➡️🔄
⬆️⬇️⏬⬇️🔄
⬆️⬆️⬇️⬅️⬅️
⏫️⬆️✅⬇️➡️
trajectorySteps 200
epision:0.093, prob1:0.9256, prob2:0.0186
-0.14870072567500864
⬆️➡️➡️⬅️➡️
⬇️⬅️➡️⬆️⬇️
⬆️⬇️⏬⬇️⬅️
⬆️⬆️➡️⬅️⬅️
⏫️⬆️✅⬅️➡