In [2]:
# value iteration
import numpy as np
import GridWorld_v1

gamma = 0.9
rows = 5
columns = 5

gridworld = GridWorld_v1.GridWorld_v1(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
gridworld.show()

value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.argmax(qtable, axis=1)

gridworld.showPolicy(policy)

pre_value = value.copy() + 1
cnt = 0

while (np.sum((pre_value - value) ** 2)) > 0.001:
    pre_value = value.copy() # 保存结果 在下一个iteration中做对比 
    cnt = cnt + 1
    # if cnt > 1000:
    #     break

    for i in range(rows * columns):
        for j in range(5):
            score, nextState = gridworld.getScore(i, j)
            qtable[i][j] = score + gamma * value[nextState]
    policy = np.argmax(qtable, axis=1)
    value = np.max(qtable, axis=1)
    print(value.reshape(rows, columns))
    print(policy.reshape(rows, columns))

print(value.reshape(rows, columns))
print(policy.reshape(rows, columns))
print(cnt)
gridworld.showPolicy(policy)

⬜️⬜️⬜️⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
🚫⬜️✅⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⏫️⬆️✅⬆️⬆️
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 1. 0.]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 1 4 3 0]]
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.9 0.  0. ]
 [0.  0.9 1.9 0.9 0. ]
 [0.9 1.9 1.9 1.9 0.9]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [0 1 2 2 0]
 [1 1 4 3 3]]
[[0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.  ]
 [0.   0.81 1.71 0.81 0.  ]
 [0.81 1.71 2.71 1.71 0.81]
 [1.71 2.71 2.71 2.71 1.71]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 2 2 2 0]
 [1 1 2 2 2]
 [1 1 4 3 3]]
[[0.    0.    0.    0.    0.   ]
 [0.    0.729 0.    0.729 0.   ]
 [0.729 1.539 2.439 1.539 0.729]
 [1.539 2.439 3.439 2.439 1.539]
 [2.439 3.439 3.439 3.439 2.439]]
[[1 1 1 1 2]
 [0 2 0 2 0]
 [1 2 2 2 2]
 [1 1 2 2 2]
 [1 1 4 3 3]]
[[0.     0.6561 0.     0.6561 0.    ]
 [0.6561 1.3851 0.6561 1.3851 0.6561]
 [1.3851 2.1951 3.0951 2.1951 1.3851]
 [

In [3]:
# (truncated) policy iteration
import numpy as np
import GridWorld_v1

gamma = 0.9
rows = 5
columns = 5

gridworld = GridWorld_v1.GridWorld_v1(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
gridworld.show()

value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.argmax(qtable, axis=1)

gridworld.showPolicy(policy)
policy = np.random.randint(0, 5, size=rows * columns) # 随机给定一个策略
gridworld.showPolicy(policy)

pre_value = value.copy() + 1
cnt = 0
while (np.sum((pre_value - value) ** 2)) > 0.001:

    truncated = 100
    pre_value = value.copy()
    
    value0 = value.copy() + 1 # value收敛

    while (np.sum((value0 - value) ** 2)) > 0.001:
        value0 = value.copy()
        truncated = truncated - 1
        if truncated < 0:
            break
        for i in range(rows * columns):
            j = policy[i]
            score, nextState = gridworld.getScore(i, j)
            value[i] = score + gamma * value0[nextState]
    
    for i in range(rows * columns):
        for j in range(5):
            score, nextState = gridworld.getScore(i, j)
            qtable[i][j] = score + gamma * value[nextState]
    
    cnt = cnt + 1
    policy = np.argmax(qtable, axis=1)
    print(value.reshape(rows, columns))
    print(policy.reshape(rows, columns))

print(value.reshape(rows, columns))
print(policy.reshape(rows, columns))
print(cnt)
gridworld.showPolicy(policy)

⬜️⬜️⬜️⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
⬜️⬜️🚫⬜️⬜️
⬜️⬜️⬜️⬜️⬜️
🚫⬜️✅⬜️⬜️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬆️⬆️⬆️
⏫️⬆️✅⬆️⬆️
➡️⬆️➡️⬅️⬆️
➡️🔄⬇️⬆️🔄
⬇️➡️⏫️⬇️⬆️
➡️⬆️⬇️➡️⬇️
⏬➡️✅⬆️➡️
[[ -8.98544422  -9.98544422   0.           0.          -9.98544422]
 [  0.           0.         -52.55496956   0.           0.        ]
 [-38.2994726  -52.55496956 -47.2994726   -7.27544422   0.        ]
 [-42.55496956 -47.2994726   -7.98544422  -8.08544422  -8.98544422]
 [ -9.98544422  -7.98544422  -9.98544422  -7.27544422  -9.98544422]]
[[2 1 1 2 2]
 [1 3 0 0 2]
 [0 0 1 0 0]
 [2 1 4 0 0]
 [1 4 1 4 3]]
[[  0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.        ]
 [-10.09560585  -0.09560585  -0.09560585   0.           0.        ]
 [ -0.09560585  -0.09560585  -0.08710537  -0.08710537  -0.08710537]]
[[1 1 1 1 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 2 0 0]
 [1 1 4 3 0]]
[[0.         0.         0.   

In [4]:
# MC Basic
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()
gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 100
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = 0
pre_qtable = qtable.copy() + 1
while (np.sum(pre_qtable - qtable) ** 2) > 0.001:
    cnt = cnt + 1
    pre_qtable = qtable.copy()
    for i in range(rows * columns):
        for j in range(5):
            Trajectory = gridworld.getTrajectoryScore(i, j, policy, trajectorySteps)
            tmp = Trajectory[trajectorySteps][2]
            for k in range(trajectorySteps - 1, -1, -1):
                tmp = Trajectory[k][2] + gamma * tmp
            qtable[i][j] = tmp
        # print(qtable)
        policy = np.eye(5)[np.argmax(qtable, axis=1)]

    gridworld.showPolicy(policy)
    print(np.sum(pre_qtable - qtable) ** 2)
print(qtable.reshape(rows * columns, 5))
print(policy.reshape(rows * columns, 5))
print(cnt)
# gridworld.showPolicy(policy)

endtime = time.time()

print(endtime - start_time)

⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
➡️⬇️⬅️⬅️⬅️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️➡️⬆️⬆️
⏫️➡️✅⬅️⬅️
67962.62038255158
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬇️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
164819.53365101654
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
41475.271303775284
➡️➡️➡️➡️⬇️
⬆️⬇️⬅️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
33129.35218753676
➡️⬇️⬇️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
55256.83467049867
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
615.4492911391343
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
0.0
[[ 4.31417095  5.90466095  5.90466095  4.31417095  5.31417095]
 [ 4.90466095  5.31417095  6.56076095  5.31417095  5.90466095]
 [ 4.31417095  5.90466095  5.90466095  5.90466095  5.31417095]
 [ 4.90466095  5.31417095  6.56076095  5.31417095  5.90466095]
 [ 4.31417095  4.31417095  5.90466095  5.90466095  5.31417095]
 [ 5.31417095  6.56076095  6.56076095  4.90466095  5.90466095]
 [ 5.90466095  5.90466095  7.28976095  5.90466095  6.56076095]
 [ 5.31417095  6.56076

In [5]:
# MC exploring starts
# every_visit strategy
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()
gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 100
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = 0
pre_qtable = qtable.copy() + 1


while (np.sum(pre_qtable - qtable) ** 2) > 0.001:
    cnt += 1
    pre_qtable = qtable.copy()
    for i in range(rows * columns):
        for j in range(5):
            qtable_rewards = [[0 for _ in range(5)] for _ in range(rows * columns)] 
            qtable_nums = [[0 for _ in range(5)] for _ in range(rows * columns)]
            Trajectory = gridworld.getTrajectoryScore(i, j, policy, trajectorySteps)
            _, _, score, _, _ = Trajectory[trajectorySteps]
            for k in range(trajectorySteps - 1, -1, -1):
                tmpstate, tmpaction, tmpscore, _, _ = Trajectory[k]
                score = tmpscore + gamma * score
                qtable_rewards[tmpstate][tmpaction] += score
                qtable_nums[tmpstate][tmpaction] += 1
                qtable[tmpstate][tmpaction] = qtable_rewards[tmpstate][tmpaction] / qtable_nums[tmpstate][tmpaction]
                policy = np.eye(5)[np.argmax(qtable, axis=1)]

    # policy = np.eye(5)[np.argmax(qtable, axis=1)]
    gridworld.showPolicy(policy)
    print(np.sum(pre_qtable - qtable) ** 2)
print(qtable.reshape(rows * columns, 5))
print(policy.reshape(rows * columns, 5))
print(cnt)

endtime = time.time()

print(endtime - start_time)


⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
⬇️⬇️⬇️⬇️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬇️⬅️⬅️
⏫️➡️✅⬅️⬅️
54.54269464581007
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏬⬇️⬇️
⬆️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
95610.46135268855
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬇️⬅️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
53927.8127717645
➡️➡️➡️⬇️⬇️
⬇️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
44153.354555450234
⬇️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
772.4980409695082
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
10.58573946965599
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
0.0
[[ 4.31417095  5.90463439  5.90463439  4.31417095  5.31417095]
 [ 4.90466095  5.31417095  6.56070487  5.31417095  5.90466095]
 [ 4.31417095  5.90463439  5.90463439  5.90463439  5.31417095]
 [ 4.90466095  5.31417095  6.56070487  5.31417095  5.90466095]
 [ 4.31417095  4.31417095  5.90463439  5.90463439  5.31417095]
 [ 5.31417095  6.56073439  6.56073439  4.90466095  5.90466095]
 [ 5.90466095  5.90466095  7.28973439  5.90466095  6.56076095]
 [ 5.31417095  6.56073439

In [8]:
# MC exploring starts
# first_visit strategy
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()

gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 100
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = 0
pre_qtable = qtable.copy() + 1


while (np.sum(pre_qtable - qtable) ** 2) > 0.001:
    cnt += 1
    pre_qtable = qtable.copy()
    for i in range(rows * columns):
        for j in range(5):
            Trajectory = gridworld.getTrajectoryScore(i, j, policy, trajectorySteps)
            _, _, score, _, _ = Trajectory[trajectorySteps]
            for k in range(trajectorySteps - 1, -1, -1):
                tmpstate, tmpaction, tmpscore, _, _ = Trajectory[k]
                score = tmpscore + gamma * score
                qtable[tmpstate][tmpaction] = score
                policy = np.eye(5)[np.argmax(qtable, axis=1)]
    
    # policy = np.eye(5)[np.argmax(qtable, axis=1)]
    gridworld.showPolicy(policy)
    print(np.sum(pre_qtable - qtable) ** 2)
print(qtable.reshape(rows * columns, 5))
print(policy.reshape(rows * columns, 5))
print(cnt)

endtime = time.time()

print(endtime - start_time)


⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
⬇️⬇️⬇️⬇️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏫️⬆️⬆️
⬆️⬆️⬇️⬅️⬅️
⏫️➡️✅⬅️⬅️
88.481218484096
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬆️⬆️
⬆️⬆️⏬⬇️⬇️
⬆️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
94878.1461414286
➡️➡️➡️➡️⬇️
⬆️⬆️⬆️⬇️⬅️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
53927.8127717645
➡️➡️➡️⬇️⬇️
⬇️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
44153.354555450234
⬇️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
772.4980409695082
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
10.58573946965599
➡️⬇️➡️⬇️⬇️
➡️⬇️➡️⬇️⬇️
➡️⬇️⏬⬇️⬇️
➡️➡️⬇️⬇️⬇️
⏩️➡️✅⬅️⬅️
0.0
[[ 4.31417095  5.90463439  5.90463439  4.31417095  5.31417095]
 [ 4.90466095  5.31417095  6.56070487  5.31417095  5.90466095]
 [ 4.31417095  5.90463439  5.90463439  5.90463439  5.31417095]
 [ 4.90466095  5.31417095  6.56070487  5.31417095  5.90466095]
 [ 4.31417095  4.31417095  5.90463439  5.90463439  5.31417095]
 [ 5.31417095  6.56073439  6.56073439  4.90466095  5.90466095]
 [ 5.90466095  5.90466095  7.28973439  5.90466095  6.56076095]
 [ 5.31417095  6.56073439 -1

In [10]:
# MC epsilon greedy
import numpy as np
import random
import GridWorld_v2
import time

start_time = time.time()

gamma = 0.9
rows = 5
columns = 5
trajectorySteps = 200
np.random.seed(521)
gridworld = GridWorld_v2.GridWorld_v2(rows=5, columns=5, forbiddenAreaNums=2, targetNums=1, seed=521, forbiddenAreaScore=-10)
# value = np.zeros(rows * columns)
qtable = np.zeros((rows * columns, 5))
policy = np.eye(5)[np.random.randint(0, 5, size=(rows * columns))]
# print(policy)

gridworld.showPolicy(policy)
cnt = [0 for _ in range(25)]

episode_num = 200
epsilon = 0.1

for episode in range(episode_num):
    if epsilon > 0.001:
        epsilon -= 0.001
    else:
        epsilon = 0.001
    
    prob1 = 1 - epsilon * (4 / 5)
    prob2 = epsilon / 5
    print("trajectorySteps",trajectorySteps)
    print(f"epision:{epsilon}, prob1:{prob1}, prob2:{prob2}")
    
    policy_epsilon = np.zeros_like(policy, dtype=float)
    policy_epsilon[policy == 1] = prob1
    policy_epsilon[policy == 0] = prob2
    i = np.random.randint(0, 24)
    j = np.random.randint(0, 4)

    # cnt = [0 for _ in range(25)]
    qtable_rewards = [[0 for _ in range(5)] for _ in range(rows * columns)] 
    qtable_nums = [[0 for _ in range(5)] for _ in range(rows * columns)]
    Trajectory = gridworld.getTrajectoryScore(i, j, policy_epsilon, trajectorySteps)
    _, _, score, _, _ = Trajectory[trajectorySteps]
    for k in range(trajectorySteps - 1, -1, -1):
        tmpstate, tmpaction, tmpscore, _, _ = Trajectory[k]
        cnt[tmpstate] += 1
        score = tmpscore + gamma * score
        qtable_rewards[tmpstate][tmpaction] += score
        qtable_nums[tmpstate][tmpaction] += 1
        qtable[tmpstate][tmpaction] = qtable_rewards[tmpstate][tmpaction] / qtable_nums[tmpstate][tmpaction]
    '''
    values = []
    for i in range(25):
        value = 0
        for j in range(5):
            value += policy_epsilon[i][j] * qtable[i][j]
        values.append(value)
    print(np.array(value).reshape(5, 5))
    print(np.array(values).mean())
    '''
    gridworld.showPolicy(policy)
    policy = np.eye(5)[np.argmax(qtable,axis=1)]
    policy_epsilon = np.zeros_like(policy, dtype=float)
    policy_epsilon[policy == 1] = prob1
    policy_epsilon[policy == 0] = prob2

    # print(np.array(cnt).reshape(5, 5))
# print(np.array(cnt).reshape(5, 5))
cnt = np.array(cnt).reshape(5, 5)
print(cnt)
endtime = time.time()

print(endtime - start_time)
print(policy_epsilon)

⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
trajectorySteps 200
epision:0.099, prob1:0.9208, prob2:0.0198
⬇️⬇️⬇️⬆️🔄
➡️⬆️⬇️⬅️⬇️
🔄⬅️⏫️➡️⬆️
🔄⬅️⬇️🔄⬆️
⏫️⬇️✅⬆️⬅️
trajectorySteps 200
epision:0.098, prob1:0.9216, prob2:0.0196
⬆️⬆️⬆️➡️⬆️
⬇️➡️➡️⬆️➡️
⬆️⬆️⏩️⬆️⬇️
⬆️⬆️⬇️⬆️➡️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.097, prob1:0.9224, prob2:0.0194
⬆️⬆️⬆️⬅️⬇️
⬇️➡️➡️➡️⬆️
⬆️⬆️⏩️⬇️🔄
⬆️⬆️⬇️⬇️⬇️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.096, prob1:0.9232, prob2:0.019200000000000002
⬆️⬇️🔄🔄➡️
⬇️⬇️🔄⬇️🔄
⬆️➡️⏩️⬇️🔄
⬆️⬆️⬇️⬇️⬇️
⏫️⬆️✅➡️⬆️
trajectorySteps 200
epision:0.095, prob1:0.9239999999999999, prob2:0.019
⬆️➡️🔄🔄➡️
⬇️⬇️🔄🔄🔄
⬆️➡️⏩️⬅️🔄
⬆️⬆️⬇️⬅️⬅️
⏫️⬆️✅⬇️➡️
trajectorySteps 200
epision:0.094, prob1:0.9248, prob2:0.0188
⬆️➡️🔄🔄➡️
⬇️⬅️➡️➡️🔄
⬆️⬇️⏬⬇️🔄
⬆️⬆️⬇️⬅️⬅️
⏫️⬆️✅⬇️➡️
trajectorySteps 200
epision:0.093, prob1:0.9256, prob2:0.0186
⬆️➡️➡️⬅️➡️
⬇️⬅️➡️⬆️⬇️
⬆️⬇️⏬⬇️⬅️
⬆️⬆️➡️⬅️⬅️
⏫️⬆️✅⬅️➡️
trajectorySteps 200
epision:0.092, prob1:0.9264, prob2:0.0184
➡️➡️🔄🔄⬅️
⬅️⬅️➡️⬆️⬇️
➡️⬇️⏬⬇️⬅️
⬅️⬆️➡️⬅️⬅️
⏫️⬆️✅⬅️➡️
trajectorySteps 200
ep